# Generated by Django 5.1.2 on 2024-10-30 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kursus')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('price', models.IntegerField(verbose_name='Harga')),
                ('image', models.ImageField(upload_to='course', verbose_name='Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Pengajar')),
            ],
            options={
                'verbose_name': 'Kursus',
                'verbose_name_plural': 'Data Kursus',
                'ordering': ['-created_at'],
            },
        ),
    ]
