# Generated by Django 5.2 on 2025-07-01 15:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tempat_lahir",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tanggal_lahir", models.DateField(blank=True, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "deskripsi",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "foto_profil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="Foto Profil",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nama Kursus")),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("price", models.IntegerField(verbose_name="Harga")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course", verbose_name="Gambar"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kuota Maksimal Siswa"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui pada"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengajar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mata Kuliah",
                "verbose_name_plural": "Data Mata Kuliah",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="judul konten")),
                (
                    "description",
                    models.TextField(default="-", verbose_name="deskripsi"),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="URL Video"
                    ),
                ),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="File"
                    ),
                ),
                (
                    "scheduled_release",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Jadwal Rilis"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lms_core.course",
                        verbose_name="matkul",
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lms_core.coursecontent",
                        verbose_name="induk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konten Matkul",
                "verbose_name_plural": "Konten Matkul",
            },
        ),
        migrations.CreateModel(
            name="ContentCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.coursecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[("std", "Siswa"), ("ast", "Asisten")],
                        default="std",
                        max_length=3,
                        verbose_name="peran",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lms_core.course",
                        verbose_name="matkul",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="siswa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber Matkul",
                "verbose_name_plural": "Subscriber Matkul",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="komentar")),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="disetujui"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.coursecontent",
                        verbose_name="konten",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.coursemember",
                        verbose_name="pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentar",
                "verbose_name_plural": "Komentar",
            },
        ),
        migrations.CreateModel(
            name="CourseCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Penyelesaian Kursus",
                "verbose_name_plural": "Data Penyelesaian Kursus",
                "unique_together": {("user", "course")},
            },
        ),
    ]
