# Generated by Django 5.1.2 on 2024-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Data Mata Kuliah'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course', verbose_name='Gambar'),
        ),
    ]
