# Generated by Django 5.2 on 2025-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="scheduled_close",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jadwal Tutup"
            ),
        ),
    ]
