# Generated by Django 5.2 on 2025-06-30 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_core", "0003_coursecontent_coursemember_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="disetujui"),
        ),
        migrations.AddField(
            model_name="course",
            name="max_students",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Kuota Maksimal Siswa"
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="scheduled_release",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jadwal Rilis"
            ),
        ),
        migrations.CreateModel(
            name="ContentCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.coursecontent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_core.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Penyelesaian Kursus",
                "verbose_name_plural": "Data Penyelesaian Kursus",
                "unique_together": {("user", "course")},
            },
        ),
    ]
