# Generated by Django 5.2 on 2025-07-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_core", "0005_user_alter_contentcompletion_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
