# Generated by Django 5.2 on 2025-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("lms_core", "0006_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="scheduled_close",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jadwal Tutup"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
