# Generated by Django 5.2 on 2025-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms_core", "0007_coursecontent_scheduled_close_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecontent",
            name="scheduled_close",
        ),
    ]
